name: Branch Naming Check

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - develop
      - main

jobs:
  check-branch-name:
    name: Validate Branch Name
    runs-on: ubuntu-latest
    
    steps:
      - name: Check branch naming convention
        run: |
          BRANCH_NAME="${{ github.ref_name }}"
          echo "Checking branch name: $BRANCH_NAME"
          
          # Allow develop and main (fallback)
          if [[ "$BRANCH_NAME" == "develop" ]] || [[ "$BRANCH_NAME" == "main" ]]; then
            echo "✅ Main branch detected"
            exit 0
          fi
          
          # Check if branch follows naming convention
          if [[ "$BRANCH_NAME" =~ ^(feature|bugfix|hotfix)/.+ ]]; then
            echo "✅ Branch name '$BRANCH_NAME' follows the naming convention"
            exit 0
          else
            echo "❌ Branch name '$BRANCH_NAME' does not follow the naming convention!"
            echo ""
            echo "📋 Required patterns:"
            echo "  - feature/<description>  (for new features)"
            echo "  - bugfix/<description>   (for bug fixes)"
            echo "  - hotfix/<description>   (for urgent production fixes)"
            echo ""
            echo "Examples:"
            echo "  ✅ feature/user-authentication"
            echo "  ✅ bugfix/fix-login-error"
            echo "  ✅ hotfix/critical-security-patch"
            echo ""
            echo "❌ Invalid: my-branch, test, cicd"
            exit 1
          fi

      - name: Success message
        if: success()
        run: |
          echo "🎉 Branch naming convention check passed!"
          echo "Branch: ${{ github.ref_name }}"
